### PR TITLE
Linear coefficients for Koop2000 ice nucleation

### PR DESCRIPTION
**Pull request by amylu00**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by trontrytel — APPROVED** [review]

**Comment by trontrytel** [comment]
@amylu00  - You will also want to bump the patch version and do a release to be able to use them in CM.jl

**Comment by nefrathenrici** [comment]
Could you add an entry to the top of the NEWS.md as well?

**Comment by amylu00** [comment]
> @amylu00 - You will also want to bump the patch version and do a release to be able to use them in CM.jl

I just bumped the patch version but I don't think I have permission to do a release?

**Comment by nefrathenrici** [comment]
> > @amylu00 - You will also want to bump the patch version and do a release to be able to use them in CM.jl
> 
> I just bumped the patch version but I don't think I have permission to do a release?

Has `@JuliaRegistrator register` failed for you in the past?

**Comment by amylu00** [comment]
@JuliaRegistrator register

**Pull request merged**
