### PR TITLE
Add distributions parameters 2-moment scheme

### PR DESCRIPTION
**Pull request by crocicc**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by crocicc** [comment]
I saw that in ClimaParams I cannot define parameters with a negative value. Since \mu for the rain distribution is negative, I defined it here as positive, and then I'll change the signs in the documentation and in the 2-moment computations. Is that okay?

**Comment by trontrytel** [comment]
> I saw that in ClimaParams I cannot define parameters with a negative value. Since \mu for the rain distribution is negative, I defined it here as positive, and then I'll change the signs in the documentation and in the 2-moment computations. Is that okay?

Why do you think you can't have negative numbers? I think we do have some negative parameters...

**Comment by crocicc** [comment]
Ok perfect, you're right! Now it's negative!

**Review by trontrytel — APPROVED** [review]
LGTM!

You will also need to change the version in the `Project.toml` https://github.com/CliMA/ClimaParams.jl/blob/d19d04343c1113575e09b1b50ee48cf355e25f70/Project.toml#L4

to `0.10.6` so that we can make a patch release.

**Pull request merged**
